# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:
#
# Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
# Pentagonal      Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
# Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

using ProjectEulerSolutions

# Calculate different pentagonal and hexagonal numbers, since every hexagonal
# number is also a triangular number.  Then find the intersection
function p045solution(n::Integer=166)::Integer

    pentvals = collect(165:n)
    hexvals = collect(143:n)
    pentset = Set(fld.(pentvals .* (3 .* pentvals .- 1), 2))
    hexset = Set(hexvals .* (2 .* hexvals .- 1))

    return maximum(intersect(pentset, hexset))
end

p045 = Problems.Problem(p045solution)

Problems.benchmark(p045, 50_000)